### PR TITLE
ATO-259: Add support for custom redirects with no active session

### PR DESCRIPTION
**Pull request by ethanmills**
## Why

We are changing application behaviour so this line will no longer be true.

## What
Remove warning about limitations of logout

### CODE REVIEW

**Comment by ethanmills** [comment]
Draft until change goes live

**Comment by huwd** [comment]
@ethanmills this is now merged, we ready for review?

Shall we ask @PippaClarkGDS for an 👀 ?

**Comment by PippaClarkGDS** [comment]
@ImogenCraigmile is the tech writer who would be able to help with a review

**Review by ImogenCraigmile — APPROVED** [review]
LGTM

**Pull request merged**
