### PR TITLE
AP-182 Document the /logout endpoint in the flow diagram

### PR DESCRIPTION
**Pull request by pauldougan**
[AP-182](https://govukverify.atlassian.net/browse/AP-182)

## What
Add the `/logout` endpoint to the how it works diagram with explanation

- add /logout endpoint to the diagram to show the role of logout in the overall flow
- enhance the text explaining the new steps in the diagram
- normalise the use of links in the explanatory text to link to appropriate content
- add additional links to the _links.erb partial
- update _changelog.erb
- ignore draw.io temporary workfiles from the git repo

image

## Why
The use of /logout is part of the overall flow of interaction with the One Login API, we need to ensure logout is seen as part of the overall journey and its omission from the diagram was inconsistent.

## Its done when
- the digram shows the interaction with the logout endpoint
- the explanation reflects this change
- there is an appropriate level of detail
- there is a mention in the changelog

## If we don't do this
- there will still be a gap in one of our key communication assets
- logout will not be presented alongside the other endpoints

## Out of scope
- backchannel logout, which is a separate server to server flow

## Technical writer support

Yes

## How to review

- run the branch locally using the docker preview
- review the diagram in context
- ensure diagram and documentation make sense and are consistent
- check the changelog makes sense

## Changelog

If this change is significant (for example, launching a new feature or deprecating a feature), you should update the changelog found at `partials/_changelog.erb`  under the heading 'Documentation updates'.

## Confirm

- [x] I have checked if any docs change here also requires updates to other repositories (ADRs / RFCs, README.md, Team Manual, elsewhere in these docs)
- [x] Where there is any overlap I have updated or opened a PR for corresponding changes

[AP-182]: https://govukverify.atlassian.net/browse/AP-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by PippaClarkGDS** [comment]
cheers @pauldougan ... Charles was also going to look at this (not sure what his GitHub username is...)

**Comment by pauldougan** [comment]
@PippaClarkGDS I have made the changes to the diagram as we discussed and updated the branch

**Comment by PippaClarkGDS** [comment]
First tech writer review done - sending to second

**Review by claireashworth — APPROVED** [review]

**Comment by PippaClarkGDS** [comment]
Both tech writers have reviewed and approved. Ok to merge once checks are working

**Pull request merged**
