### PR TITLE
Self service docs

### PR DESCRIPTION
**Pull request by PippaClarkGDS**
## Why

Self-service portal is being launched. We need to update the tech docs to reflect this new journey. 

## What

This PR covers the new user journey for self-service, along with updated journey for identity clients, and bug fixes. 

## Technical writer support

This will go through tech writer review. 

## How to review

Check all info is correct from a technical POV, including the user journey.

### CODE REVIEW

**Comment by huwd** [comment]
@sabrinaharris / @elenaschwan / @ImogenCraigmile
Is this work stale and can we close down the PR?

Can keep the branch and re-open this when it's ready to merge?

**Comment by huwd** [comment]
@sabrinaharris / @ImogenCraigmile how would you feel about me closing this as a PR, doesn't seem related to a current change we're considering?

I can keep the branch if we'd want to update and revive the work later?

**Comment by pauldougan** [comment]
@huwd for hygiene reasons I vote for deleting the PR whilst retaining the branch

**Comment by sabrinaharris** [comment]
Closing this because the admin tool release was much later than planned. This means we need to redo any updates (given the number of other changes to the docs since then) and check the functionality and scope of the admin tool again.

**Pull request closed without merging**
