### PR TITLE
Remove redundant GOV.UK PaaS files

### PR DESCRIPTION
**Pull request by pauldougan**
## Why

The docs used to be hosted on [GOV.UK PaaS](https://cloud.service.gov.uk) but is now migrated to AWS ECS and there is some residual junk left over that is redundant.

## What

delete `Staticfile` and `manifest.yml`

## Technical writer support

Do you need a tech writer's support, for example to review your PR?   - no

## How to review

- Ensure it still runs locally using the local ruby
- Ensure it still runs locally using Docker

### CODE REVIEW

**Comment by pauldougan** [comment]
Hey @elenaschwan one final merge ...

**Review by huwd — APPROVED** [review]
Had a bit of rebuild troubles, but moment I rebased against main it went away.
I think that's just based on the older branch we've spun off here.

So looks good to me

**Comment by huwd** [comment]
@pauldougan this duplicates [this](https://github.com/govuk-one-login/authentication-tech-docs/pull/150) right?

could we close the other one if so?

**Review by elenaschwan — APPROVED** [review]
Looks good to me!

**Comment by pauldougan** [comment]
@huwd yes need to tidy up the other one which was from a branch in my fork. Will retire thr fork and tidy up the issues etc

**Comment by pauldougan** [comment]
Ok I killed my fork now

**Pull request merged**
